server:
  port: 8080


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/resume?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.suda.resume.pojo
